// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         string             `json:"id"`
	Name       string             `json:"name"`
	KeyHash    string             `json:"key_hash"`
	CreatedBy  pgtype.Text        `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	IsActive   bool               `json:"is_active"`
}

type Job struct {
	ID           string             `json:"id"`
	Type         string             `json:"type"`
	Payload      []byte             `json:"payload"`
	Status       string             `json:"status"`
	Attempts     int32              `json:"attempts"`
	MaxAttempts  int32              `json:"max_attempts"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	ScheduledAt  pgtype.Timestamptz `json:"scheduled_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
