// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeJob = `-- name: CompleteJob :exec
UPDATE jobs
SET 
    status = 'completed',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) CompleteJob(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, completeJob, id)
	return err
}

const countJobsByStatus = `-- name: CountJobsByStatus :one
SELECT COUNT(*) FROM jobs
WHERE status = $1
`

func (q *Queries) CountJobsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countJobsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    id,
    type,
    payload,
    status,
    max_attempts
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, type, payload, status, attempts, max_attempts, error_message, scheduled_at, created_at, updated_at
`

type CreateJobParams struct {
	ID          string `json:"id"`
	Type        string `json:"type"`
	Payload     []byte `json:"payload"`
	Status      string `json:"status"`
	MaxAttempts int32  `json:"max_attempts"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.ID,
		arg.Type,
		arg.Payload,
		arg.Status,
		arg.MaxAttempts,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ErrorMessage,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const dequeueJob = `-- name: DequeueJob :one
UPDATE jobs
SET 
    status = 'processing',
    updated_at = NOW()
WHERE id = (
    SELECT id
    FROM jobs
    WHERE status = 'pending'
        AND scheduled_at <= NOW()
    ORDER BY scheduled_at ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, type, payload, status, attempts, max_attempts, error_message, scheduled_at, created_at, updated_at
`

func (q *Queries) DequeueJob(ctx context.Context) (Job, error) {
	row := q.db.QueryRow(ctx, dequeueJob)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ErrorMessage,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failJob = `-- name: FailJob :exec
UPDATE jobs
SET 
    status = $2,
    attempts = $3,
    error_message = $4,
    scheduled_at = $5,
    updated_at = NOW()
WHERE id = $1
`

type FailJobParams struct {
	ID           string             `json:"id"`
	Status       string             `json:"status"`
	Attempts     int32              `json:"attempts"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	ScheduledAt  pgtype.Timestamptz `json:"scheduled_at"`
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.db.Exec(ctx, failJob,
		arg.ID,
		arg.Status,
		arg.Attempts,
		arg.ErrorMessage,
		arg.ScheduledAt,
	)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, type, payload, status, attempts, max_attempts, error_message, scheduled_at, created_at, updated_at FROM jobs
WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ErrorMessage,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, type, payload, status, attempts, max_attempts, error_message, scheduled_at, created_at, updated_at FROM jobs
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListJobsParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.ErrorMessage,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
