// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CompleteJob(ctx context.Context, id string) error
	CountJobsByStatus(ctx context.Context, status string) (int64, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	DequeueJob(ctx context.Context) (Job, error)
	FailJob(ctx context.Context, arg FailJobParams) error
	GetJob(ctx context.Context, id string) (Job, error)
	ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error)
}

var _ Querier = (*Queries)(nil)
